package cn.duskrain;

import java.util.*;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.item.*;
import net.minecraft.world.level.*;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.phys.Vec3;
import net.minecraftforge.gametest.*;

@GameTestHolder(DuskRain.ID)
@PrefixGameTestTemplate(false)
public final class V13Tests {
    @GameTest(template="empty",timeoutTicks=200) public static void permanent_purchases_stale_clicks_and_health_ratio(GameTestHelper h){
        var p=IntegrationTests.servicePlayer(h,"DRPermanent","treasures");var r=Store.of(p);r.money=100000;long expected=r.money;
        for(int rank=0;rank<5;rank++){String id="treasure_health_"+rank;Boosts.purchase(p,id,1,false);expected-=Boosts.config.rankPrices[rank];h.assertTrue(r.upgrades[0]==rank+1&&r.money==expected,"Rank advances once at the stated price");Boosts.purchase(p,id,1,false);h.assertTrue(r.upgrades[0]==rank+1&&r.money==expected,"Stale purchase cannot advance or charge twice");}
        r.upgrades[1]=5;r.upgrades[2]=5;r.upgrades[3]=5;Skills.attributes(p);p.setHealth(p.getMaxHealth()*.4f);float peaceful=p.getMaxHealth();
        for(int i=0;i<8;i++){r.combatUntil=System.currentTimeMillis()+15000;Skills.attributes(p);h.assertTrue(Math.abs(p.getHealth()/p.getMaxHealth()-.4)<.0001&&p.getMaxHealth()<peaceful,"PVP permanently boosted max health changes without healing");r.combatUntil=0;Skills.attributes(p);h.assertTrue(Math.abs(p.getHealth()/p.getMaxHealth()-.4)<.0001,"Leaving PVP cannot heal by toggling max health");}
        var saved=Profile.load(r.save());h.assertTrue(Arrays.equals(saved.upgrades,r.upgrades)&&saved.money==r.money,"UUID profile persists all ranks and exact remaining money");h.succeed();
    }
    @GameTest(template="empty") public static void elixirs_online_timer_refresh_and_death(GameTestHelper h){var p=IntegrationTests.player(h,"DRElixirs");Profile r=Store.of(p);var potion=Boosts.ITEMS.get(0).get();p.setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(potion,2));potion.use(p.level(),p,InteractionHand.MAIN_HAND);h.assertTrue(r.elixirs[0]==24000&&p.getMainHandItem().getCount()==1,"Use consumes one elixir and starts 20 online minutes");Boosts.tick(p);h.assertTrue(r.elixirs[0]==23999,"Online tick decrements timer");Profile restored=Profile.load(r.save());h.assertTrue(restored.elixirs[0]==23999,"Offline persistence does not advance timer");p.getCooldowns().removeCooldown(potion);potion.use(p.level(),p,InteractionHand.MAIN_HAND);h.assertTrue(r.elixirs[0]==24000&&Boosts.speed(r)==.1,"Same elixir refreshes rather than stacks");r.upgrades[0]=2;Boosts.died(p);h.assertTrue(Arrays.stream(r.elixirs).sum()==0&&r.upgrades[0]==2,"Death removes temporary gains, retains permanent ranks");h.succeed();}
    @GameTest(template="empty") public static void city_body_additive_speed_and_skill_unlocks(GameTestHelper h){var p=IntegrationTests.servicePlayer(h,"DRBodyMobility","master");Profile r=Store.of(p);r.school=3;CityMobility.tick(p);Skills.attributes(p);double base=p.getAttribute(Attributes.MOVEMENT_SPEED).getBaseValue();h.assertTrue(Math.abs(p.getAttributeValue(Attributes.MOVEMENT_SPEED)-base*1.65)<.00001,"City +40% and body +25% add to +65%");h.assertTrue(Math.abs(p.getAttributeValue(Attributes.KNOCKBACK_RESISTANCE)-.6)<.001,"Body resistance is 60%");h.assertTrue(Skills.heldValid(p),"Body can cast empty-handed");
        for(int school=1;school<=3;school++){r.school=school;r.stage=2;r.mana=1000;for(int slot=0;slot<3;slot++){p.setItemInHand(InteractionHand.MAIN_HAND,school==3?ItemStack.EMPTY:new ItemStack(Content.ARTIFACTS.get((school-1)*6).get()));Skills.clear(p.getUUID());int before=r.mana;Skills.cast(p,slot);h.assertTrue(r.mana==before-Skills.cost(r,slot)&&Gameplay.COOLDOWNS.get(p.getUUID())[slot]>System.currentTimeMillis(),"All nine actives unlock within first realm and charge stated mana");}Skills.clear(p.getUUID());}
        h.succeed();
    }
    @GameTest(template="empty",timeoutTicks=200) public static void guild_roles_archiving_and_nonreused_ids(GameTestHelper h){var founder=IntegrationTests.servicePlayer(h,"DRGuildFounder","guild");var member=IntegrationTests.player(h,"DRGuildMember");var other=IntegrationTests.player(h,"DRGuildOther");var data=GuildData.get(founder.server);int first=data.nextId;try{
        Store.of(founder).stage=16;Guilds.act(founder,"create","验证宗门");h.assertTrue(data.of(founder.getUUID())==null,"Founder requires final stage, not merely final realm");Store.of(founder).stage=17;Guilds.act(founder,"create","验证宗门");var g=data.of(founder.getUUID());h.assertTrue(g!=null&&!g.ready&&g.id==first,"Creation assigns a stable, unready plot");Guilds.act(founder,"invite",member.getUUID().toString());Guilds.act(member,"accept","");h.assertTrue(g.member(member.getUUID()),"Low-stage member accepts authorized invite");g.ready=true;
        var level=founder.server.getLevel(Guilds.DIM);BlockPos inside=new BlockPos(g.x()+20,65,g.z()+20);h.assertTrue(Guilds.edit(member,level,inside)&&!Guilds.edit(other,level,inside),"Member-only building authority is checked at target position");h.assertTrue(!Guilds.edit(member,level,inside.offset(1024,0,0)),"Member cannot build in another isolated region");h.assertTrue(!Guilds.edit(member,level,new BlockPos(g.x(),64,g.z()+112)),"Return platform remains protected");
        Guilds.act(founder,"transfer",member.getUUID().toString());h.assertTrue(g.leader.equals(founder.getUUID()),"Leadership transfer also requires final stage");Guilds.act(founder,"kick",member.getUUID().toString());h.assertTrue(!Guilds.edit(member,level,inside),"Removal immediately revokes building authority");Guilds.act(founder,"confirm","");h.assertTrue(!g.archived,"Unconfirmed disband cannot archive");Guilds.act(founder,"disband","");Guilds.act(founder,"confirm","");h.assertTrue(g.archived&&data.of(founder.getUUID())==null,"Confirmed disband archives and removes membership");var restored=GuildData.load(data.save(new CompoundTag()));h.assertTrue(restored.guilds.get(first).archived&&restored.nextId>first,"Restart retains archive and cannot recycle its ID");
    }finally{data.guilds.remove(first);Guilds.CONFIRM.clear();Guilds.INVITES.clear();Guilds.ENTER_WHEN_READY.clear();data.setDirty();}h.succeed();}
    @GameTest(template="empty",timeoutTicks=200) public static void guild_generation_stamp_preserves_builds(GameTestHelper h){var l=h.getLevel().getServer().getLevel(Guilds.DIM);var g=new GuildData.Guild(9901,"生成验证",UUID.randomUUID());Guilds.generateChunk(l,g,0);BlockPos floor=new BlockPos(g.x()-120,64,g.z()-120);h.assertTrue(l.getBlockState(floor.below(3)).is(Blocks.BEDROCK),"Generated plot has a void-safe foundation");l.setBlock(floor,Blocks.DIAMOND_BLOCK.defaultBlockState(),2);Guilds.generateChunk(l,g,0);h.assertTrue(l.getBlockState(floor).is(Blocks.DIAMOND_BLOCK),"Resuming stamped chunk never overwrites a member's build");h.succeed();}
    @GameTest(template="empty") public static void adjacent_claims_external_outline_and_relations(GameTestHelper h){var p=IntegrationTests.player(h,"DRBorderOwner");var visitor=IntegrationTests.player(h,"DRBorderVisitor");Store data=Store.get(p.server);int cx=p.chunkPosition().x,cz=p.chunkPosition().z;long k1=ChunkPos.asLong(cx,cz),k2=ChunkPos.asLong(cx+1,cz);var before1=data.claims.get(k1);var before2=data.claims.get(k2);try{data.claims.put(k1,new Store.Claim(p.getUUID()));data.claims.put(k2,new Store.Claim(p.getUUID()));p.serverLevel().getChunk(cx+1,cz);visitor.setPos(p.getX(),p.getY(),p.getZ());var mine=ClaimBorders.nearby(p).edges().stream().filter(e->e.owner().equals(p.getGameProfile().getName())).toList();h.assertTrue(mine.size()==6&&mine.stream().allMatch(e->e.relation()==0),"Two adjacent chunks have six external edges and no internal seam");var seen=ClaimBorders.nearby(visitor).edges();h.assertTrue(seen.stream().filter(e->e.owner().equals(p.getGameProfile().getName())).allMatch(e->e.relation()==2),"Other players receive red ownership edges");for(long k:new long[]{k1,k2})data.claims.get(k).members.add(visitor.getUUID());h.assertTrue(ClaimBorders.nearby(visitor).edges().stream().filter(e->e.owner().equals(p.getGameProfile().getName())).allMatch(e->e.relation()==1),"Trusted visitors receive gold edges");}finally{if(before1==null)data.claims.remove(k1);else data.claims.put(k1,before1);if(before2==null)data.claims.remove(k2);else data.claims.put(k2,before2);}h.succeed();}
}
