package cn.duskrain;

import java.util.*;
import net.minecraft.network.FriendlyByteBuf;
import net.minecraft.server.level.ServerPlayer;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.fml.DistExecutor;
import net.minecraftforge.network.*;
import net.minecraftforge.network.simple.SimpleChannel;

public final class V14Network {
    public static void to(ServerPlayer p,Object value){if(!(p instanceof net.minecraftforge.common.util.FakePlayer))Network.CHANNEL.send(PacketDistributor.PLAYER.with(()->p),value);}
    public static void init(SimpleChannel ch){
        ch.registerMessage(13,SwordFlight.Input.class,(m,b)->b.writeByte(m.bits()),b->new SwordFlight.Input(b.readUnsignedByte()),(m,c)->{var ctx=c.get();ctx.enqueueWork(()->{if(ctx.getSender()!=null)SwordFlight.input(ctx.getSender(),m);});ctx.setPacketHandled(true);},Optional.of(NetworkDirection.PLAY_TO_SERVER));
        ch.registerMessage(14,SwordFlight.State.class,(m,b)->{b.writeBoolean(m.flying());b.writeBoolean(m.landing());b.writeLong(m.rental());b.writeInt(m.school());b.writeInt(m.stage());},b->new SwordFlight.State(b.readBoolean(),b.readBoolean(),b.readLong(),b.readInt(),b.readInt()),(m,c)->{c.get().enqueueWork(()->DistExecutor.unsafeRunWhenOn(Dist.CLIENT,()->()->FlightClient.state=m));c.get().setPacketHandled(true);},Optional.of(NetworkDirection.PLAY_TO_CLIENT));
        ch.registerMessage(15,PlayerTitles.View.class,(m,b)->{b.writeVarInt(m.titles().size());for(var t:m.titles()){b.writeInt(t.entity());b.writeUUID(t.uuid());b.writeUtf(t.text(),128);b.writeInt(t.stage());b.writeInt(t.school());}},b->{int n=b.readVarInt();if(n<0||n>256)throw new IllegalArgumentException("Title count");var ts=new ArrayList<PlayerTitles.Title>();for(int i=0;i<n;i++)ts.add(new PlayerTitles.Title(b.readInt(),b.readUUID(),b.readUtf(128),b.readInt(),b.readInt()));return new PlayerTitles.View(ts);},(m,c)->{c.get().enqueueWork(()->DistExecutor.unsafeRunWhenOn(Dist.CLIENT,()->()->FlightClient.titles(m)));c.get().setPacketHandled(true);},Optional.of(NetworkDirection.PLAY_TO_CLIENT));
        ch.registerMessage(11,MarketStock.View.class,V14Network::writeMarket,V14Network::readMarket,(m,c)->{c.get().enqueueWork(()->DistExecutor.unsafeRunWhenOn(Dist.CLIENT,()->()->MarketChestScreen.receive(m)));c.get().setPacketHandled(true);},Optional.of(NetworkDirection.PLAY_TO_CLIENT));
        ch.registerMessage(12,MarketStock.Request.class,(m,b)->{b.writeUtf(m.verb(),16);b.writeInt(m.site());b.writeUUID(m.id());b.writeInt(m.slot());b.writeInt(m.quantity());b.writeLong(m.price());b.writeLong(m.revision());b.writeLong(m.sequence());},b->new MarketStock.Request(b.readUtf(16),b.readInt(),b.readUUID(),b.readInt(),b.readInt(),b.readLong(),b.readLong(),b.readLong()),(m,c)->{var ctx=c.get();ctx.enqueueWork(()->{if(ctx.getSender()!=null)MarketStock.request(ctx.getSender(),m);});ctx.setPacketHandled(true);},Optional.of(NetworkDirection.PLAY_TO_SERVER));
        ch.registerMessage(9,Enchanting.View.class,V14Network::writeEnchant,V14Network::readEnchant,(m,c)->{c.get().enqueueWork(()->DistExecutor.unsafeRunWhenOn(Dist.CLIENT,()->()->EnchanterScreen.receive(m)));c.get().setPacketHandled(true);},Optional.of(NetworkDirection.PLAY_TO_CLIENT));
        ch.registerMessage(10,Enchanting.Request.class,(m,b)->{b.writeBoolean(m.apply());b.writeInt(m.slot());b.writeInt(m.enchant());b.writeLong(m.quote());},b->new Enchanting.Request(b.readBoolean(),b.readInt(),b.readInt(),b.readLong()),(m,c)->{var ctx=c.get();ctx.enqueueWork(()->{if(ctx.getSender()!=null)Enchanting.handle(ctx.getSender(),m);});ctx.setPacketHandled(true);},Optional.of(NetworkDirection.PLAY_TO_SERVER));
    }
    static void writeMarket(MarketStock.View v,FriendlyByteBuf b){if(v.rows().size()>27)throw new IllegalArgumentException("Market view exceeds 27 rows");b.writeInt(v.site());b.writeUtf(v.name(),128);b.writeUtf(v.owner(),64);b.writeBoolean(v.mine());b.writeBoolean(v.vacant());b.writeLong(v.money());b.writeLong(v.revision());b.writeVarInt(v.rows().size());for(var r:v.rows()){b.writeUUID(r.id());b.writeItem(r.sample());b.writeInt(r.quantity());b.writeLong(r.price());b.writeLong(r.version());b.writeBoolean(r.legacy());}}
    static MarketStock.View readMarket(FriendlyByteBuf b){int site=b.readInt();String name=b.readUtf(128),owner=b.readUtf(64);boolean mine=b.readBoolean(),vacant=b.readBoolean();long money=b.readLong(),revision=b.readLong();int n=b.readVarInt();if(n<0||n>27)throw new IllegalArgumentException("Market row count");List<MarketStock.Row> rows=new ArrayList<>();for(int i=0;i<n;i++)rows.add(new MarketStock.Row(b.readUUID(),b.readItem(),b.readInt(),b.readLong(),b.readLong(),b.readBoolean()));return new MarketStock.View(site,name,owner,mine,vacant,money,revision,rows);}
    static void writeEnchant(Enchanting.View v,FriendlyByteBuf b){if(v.choices().size()>8)throw new IllegalArgumentException("Enchant view exceeds 8 choices");b.writeLong(v.quote());b.writeInt(v.slot());b.writeItem(v.item());b.writeLong(v.money());b.writeVarInt(v.choices().size());for(var c:v.choices()){b.writeInt(c.id());b.writeInt(c.next());b.writeLong(c.price());b.writeInt(c.lapis());b.writeInt(c.sand());b.writeInt(c.levels());b.writeInt(c.stage());b.writeBoolean(c.enabled());b.writeUtf(c.reason(),128);b.writeDouble(c.effect());}}
    static Enchanting.View readEnchant(FriendlyByteBuf b){long quote=b.readLong();int slot=b.readInt();var item=b.readItem();long money=b.readLong();int n=b.readVarInt();if(n<0||n>8)throw new IllegalArgumentException("enchant choices");List<Enchanting.Choice> list=new ArrayList<>();for(int i=0;i<n;i++)list.add(new Enchanting.Choice(b.readInt(),b.readInt(),b.readLong(),b.readInt(),b.readInt(),b.readInt(),b.readInt(),b.readBoolean(),b.readUtf(128),b.readDouble()));return new Enchanting.View(quote,slot,item,money,list);}
}
