package cn.duskrain;
import java.util.*;
import io.netty.buffer.Unpooled;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.network.FriendlyByteBuf;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.item.*;
import net.minecraft.world.item.enchantment.*;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.phys.Vec3;
import net.minecraftforge.gametest.*;
@GameTestHolder(DuskRain.ID) @PrefixGameTestTemplate(false)
public final class V14Tests {
 static void check(GameTestHelper h,boolean ok,String s){h.assertTrue(ok,s);}
 @GameTest(template="empty") public static void vanilla_anvil_and_grindstone_preserve_binding(GameTestHelper h){
  var p=IntegrationTests.player(h,"DRVanillaEnchant");p.experienceLevel=100;
  ItemStack blade=new ItemStack(Content.ARTIFACTS.get(0).get());Content.bind(blade,p);blade.setHoverName(net.minecraft.network.chat.Component.literal("保留名称"));blade.enchant(MysticEnchants.ALL.get(0).get(),1);blade.enchant(Enchantments.UNBREAKING,2);
  var anvil=new net.minecraft.world.inventory.AnvilMenu(1,p.getInventory());anvil.getSlot(0).set(blade.copy());anvil.getSlot(1).set(EnchantedBookItem.createForEnchantment(new EnchantmentInstance(MysticEnchants.ALL.get(0).get(),1)));anvil.setItemName("保留名称");anvil.createResult();var result=anvil.getSlot(2).getItem();
  check(h,!result.isEmpty()&&MysticEnchants.level(result,0)==2&&EnchantmentHelper.getItemEnchantmentLevel(Enchantments.UNBREAKING,result)==2&&Content.owned(result,p),"Vanilla anvil merges exclusive levels and preserves vanilla enchant/binding");
  var stone=new net.minecraft.world.inventory.GrindstoneMenu(2,p.getInventory());stone.getSlot(0).set(result.copy());stone.slotsChanged(stone.getSlot(0).container);var clean=stone.getSlot(2).getItem();DuskRain.LOG.info("V14_GRIND input={} output={}",result.save(new CompoundTag()),clean.save(new CompoundTag()));check(h,!clean.isEmpty()&&MysticEnchants.count(clean)==0&&EnchantmentHelper.getEnchantments(clean).isEmpty()&&Content.owned(clean,p)&&clean.getHoverName().getString().equals("保留名称"),"Vanilla grindstone removes noncurse enchants but preserves name/binding");
  var book=EnchantedBookItem.createForEnchantment(new EnchantmentInstance(MysticEnchants.ALL.get(0).get(),1));var books=new net.minecraft.world.inventory.AnvilMenu(3,p.getInventory());books.getSlot(0).set(book.copy());books.getSlot(1).set(book.copy());books.createResult();check(h,EnchantmentHelper.getEnchantments(books.getSlot(2).getItem()).getOrDefault(MysticEnchants.ALL.get(0).get(),0)==2,"Admin-authored books remain legal in the vanilla anvil");h.succeed();
 }
 @GameTest(template="empty") public static void inscription_missing_resources_no_charge_and_no_item_escrow(GameTestHelper h){var city=h.getLevel().getServer().getLevel(Gameplay.CITY);try(var peer=new NativeAcceptanceTests.Peer(city,"DRMissingRune",Services.find("enchanter").position().add(-2,0,2))){var p=peer.player;var r=Store.of(p);r.stage=20;r.money=100000;p.experienceLevel=100;var blade=new ItemStack(Content.ARTIFACTS.get(0).get());p.getInventory().setItem(0,blade);p.getInventory().setItem(1,new ItemStack(Items.LAPIS_LAZULI,64));Enchanting.select(p,0);var q=Enchanting.QUOTES.get(p.getUUID());Enchanting.handle(p,new Enchanting.Request(true,0,0,q.id()));check(h,r.money==100000&&p.experienceLevel==100&&MysticEnchants.count(blade)==0&&Gameplay.count(p,Items.LAPIS_LAZULI)==64,"Missing rune sand spends nothing and selected item stays in inventory");p.getInventory().setItem(2,new ItemStack(MysticEnchants.SAND.get(),64));Enchanting.select(p,0);q=Enchanting.QUOTES.get(p.getUUID());blade.setDamageValue(1);Enchanting.handle(p,new Enchanting.Request(true,0,0,q.id()));check(h,r.money==100000&&MysticEnchants.count(blade)==0,"Item mutation invalidates old quote without charging");}h.succeed();}
 @GameTest(template="empty") public static void twenty_one_stage_ids_and_legacy_progress(GameTestHelper h){
  for(int school=1;school<=3;school++)for(int tier=0;tier<6;tier++){var item=(Content.Artifact)Content.ARTIFACTS.get((school-1)*6+tier).get();check(h,item.school==school&&item.tier==tier,"Legacy artifact indices preserved");}
  for(int s=0;s<21;s++){Profile r=new Profile();r.stage=s;r.money=321;r.main=9;r.xp=127;r.flightTicks=777;var l=Profile.load(r.save());check(h,l.stage==s&&l.money==321&&l.xp==127&&l.main==9&&l.flightTicks==777,"Stage/profile roundtrip "+s);}
  h.succeed();
 }
 @GameTest(template="empty") public static void inscription_all_levels_preserve_original_nbt_and_reject_replay(GameTestHelper h){
  var city=h.getLevel().getServer().getLevel(Gameplay.CITY);try(var peer=new NativeAcceptanceTests.Peer(city,"DRInscription",Services.find("enchanter").position().add(-2,0,2))){var p=peer.player;var r=Store.of(p);r.stage=20;r.money=10000000;int operations=0;
   for(int id=0;id<8;id++){
    Item item=id==0?Content.ARTIFACTS.get(0).get():id==1?Content.ARTIFACTS.get(6).get():id==2?Content.ARTIFACTS.get(12).get():Outfits.item(0,id==4?ArmorItem.Type.HELMET:id>=6?ArmorItem.Type.BOOTS:ArmorItem.Type.CHESTPLATE);
    ItemStack gear=new ItemStack(item);gear.setDamageValue(7);gear.setHoverName(net.minecraft.network.chat.Component.literal("原名·验收"));Content.bind(gear,p);gear.enchant(Enchantments.UNBREAKING,1);p.getInventory().setItem(0,gear);p.getInventory().setItem(1,new ItemStack(Items.LAPIS_LAZULI,64));p.getInventory().setItem(2,new ItemStack(MysticEnchants.SAND.get(),64));p.experienceLevel=200;
    for(int k=1;k<=AscensionRules.current.enchantMax[id];k++){
     Enchanting.select(p,0);var q=Enchanting.QUOTES.get(p.getUUID());long oldMoney=r.money;int lapis=Gameplay.count(p,Items.LAPIS_LAZULI),levels=p.experienceLevel;
     Enchanting.handle(p,new Enchanting.Request(true,0,id,q.id()));check(h,MysticEnchants.level(gear,id)==k&&r.money==oldMoney-200L*k*k&&Gameplay.count(p,Items.LAPIS_LAZULI)==lapis-4*k&&p.experienceLevel==levels-2*k,"Exact upgrade cost "+id+"/"+k);
     long paid=r.money;Enchanting.handle(p,new Enchanting.Request(true,0,id,q.id()));check(h,r.money==paid,"Quote cannot charge twice");operations++;
    }
    check(h,gear.getDamageValue()==7&&gear.getHoverName().getString().equals("原名·验收")&&EnchantmentHelper.getItemEnchantmentLevel(Enchantments.UNBREAKING,gear)==1&&Content.owned(gear,p),"Original damage, name, vanilla enchant and binding preserved");
    Enchanting.select(p,0);var q=Enchanting.QUOTES.get(p.getUUID());long paid=r.money;Enchanting.handle(p,new Enchanting.Request(true,0,id,q.id()));check(h,r.money==paid,"Maxed inscription cannot charge");
   }DuskRain.LOG.info("V14_ENCHANT allUpgradeLevels={} replay=max=nbt=PASS",operations);
  }h.succeed();
 }
 @GameTest(template="empty") public static void god_progression_resources_pvp_ratio_and_large_boss(GameTestHelper h){
  var p=IntegrationTests.player(h,"DRGodTest");var r=Store.of(p);r.stage=17;r.school=1;r.main=24;r.xp=1000000;r.money=4321;Skills.attributes(p);float baseline=p.getMaxHealth();
  for(int stage=17;stage<20;stage++){int i=stage-17;p.getInventory().setItem(1,new ItemStack(i==0?Ascension.CORE.get():Ascension.CRYSTAL.get(),AscensionRules.current.cores[i]));p.getInventory().setItem(2,new ItemStack(Items.NETHER_STAR,AscensionRules.current.stars[i]));int xp=r.xp;check(h,Ascension.eligible(p,false),"Complete resource loop available");check(h,Ascension.complete(p,stage),"God rank commits");check(h,r.stage==stage+1&&r.xp==xp-Rules.current.stageXp[stage]&&r.money==4321,"Successful advancement consumes XP/materials only");check(h,!Ascension.complete(p,stage),"Repeated completion cannot advance twice");Skills.attributes(p);check(h,Math.abs(p.getMaxHealth()-baseline-AscensionRules.current.health[i])<.01,"God health is relative to stage 17, not cumulative");p.setHealth(p.getMaxHealth()*.4f);r.combatUntil=System.currentTimeMillis()+15000;Skills.attributes(p);check(h,Math.abs(p.getMaxHealth()-baseline-AscensionRules.current.health[i]*.2)<.01&&Math.abs(p.getHealth()/p.getMaxHealth()-.4)<.001,"PVP compression preserves health ratio");r.combatUntil=0;Skills.attributes(p);check(h,Math.abs(p.getHealth()/p.getMaxHealth()-.4)<.001,"Leaving PVP grants no ratio healing");}
  var boss=TrialBoss.SENTINEL.get().create(h.getLevel());for(int health:AscensionRules.current.trialHealth){boss.divineMax(health);boss.setHealth(health);check(h,boss.getMaxHealth()==health&&boss.getHealth()==health,"Native synced guardian health exceeds vanilla attribute ceiling: "+health);}boss.discard();h.succeed();
 }
 @GameTest(template="empty") public static void market_twenty_seven_slots_nbt_stock_conflicts_and_recovery(GameTestHelper h){
  var city=h.getLevel().getServer().getLevel(Gameplay.CITY);var site=PlayerMarket.SITES.get(10);city.getChunkAt(site.counter());Vec3 at=Vec3.atBottomCenterOf(site.counter().offset(-2,0,1));try(var seller=new NativeAcceptanceTests.Peer(city,"DRStockSeller",at);var buyer=new NativeAcceptanceTests.Peer(city,"DRStockBuyer",at)){
   var data=Store.get(seller.player.server);var previous=data.market.remove(site.id());try{var shop=PlayerMarket.shop(data,site.id());shop.owner=seller.player.getUUID();shop.ownerName="离线卖家";Store.of(buyer.player).money=100000;
    for(int i=0;i<27;i++){var stack=new ItemStack(Items.PAPER,5);stack.setHoverName(net.minecraft.network.chat.Component.literal("独立商品"+i));seller.player.getInventory().setItem(0,stack);request(seller.player,shop,site,"list",MarketStock.NONE,0,5,11);}
    check(h,shop.stock.size()==27,"27 independently named products accepted");long rev=shop.revision;seller.player.getInventory().setItem(0,new ItemStack(Items.DIAMOND));request(seller.player,shop,site,"list",MarketStock.NONE,0,1,99);check(h,shop.stock.size()==27&&shop.revision==rev,"28th rejected without taking item");
    var first=shop.stock.values().iterator().next();long money=Store.of(buyer.player).money;var req=new MarketStock.Request("buy",site.id(),first.id,0,2,0,shop.revision,9999999);MarketStock.request(buyer.player,req);check(h,first.quantity==3&&Store.of(buyer.player).money==money-22&&Store.of(seller.player).money==122,"Partial sale and offline credit conserve assets");MarketStock.request(buyer.player,req);check(h,first.quantity==3,"Same request not replayed");MarketStock.request(buyer.player,new MarketStock.Request("buy",site.id(),first.id,0,3,0,req.revision(),99999999));check(h,first.quantity==3,"Stale quote cannot buy changed stock");
    var saved=data.save(new CompoundTag());var loaded=Store.load(saved);check(h,loaded.market.get(site.id()).stock.size()==27&&loaded.market.get(site.id()).stock.get(first.id).quantity==3,"Escrow persists exact quantities");
    buyer.player.getInventory().clearContent();buyer.player.getPersistentData().putLong("DuskRainTransaction",0);Transactions.login(buyer.player);check(h,Gameplay.count(buyer.player,Items.PAPER)==2,"Published transaction restores unsaved inventory after simulated crash");Transactions.login(buyer.player);check(h,Gameplay.count(buyer.player,Items.PAPER)==2,"Recovery is idempotent");
    DuskRain.LOG.info("V14_MARKET 27slots partial duplicate staleQuote offlineCredit recovery=PASS");
   }finally{data.market.remove(site.id());if(previous!=null)data.market.put(site.id(),previous);}
  }h.succeed();
 }
 static void request(net.minecraft.server.level.ServerPlayer p,PlayerMarket.Shop shop,PlayerMarket.Site site,String verb,UUID id,int slot,int qty,long price){MarketStock.request(p,new MarketStock.Request(verb,site.id(),id,slot,qty,price,shop.revision,MarketStock.SEEN.getOrDefault(p.getUUID(),0L)+1));}
 @GameTest(template="empty") public static void chinese_guild_creation_rename_and_god_eligibility(GameTestHelper h){var city=h.getLevel().getServer().getLevel(Gameplay.CITY);try(var peer=new NativeAcceptanceTests.Peer(city,"DRChineseGuild",Services.find("guild").position().add(-2,0,2))){var p=peer.player;Store.of(p).stage=20;var data=GuildData.get(p.server);int id=data.nextId;try{IntegrationTests.command(p,"dr guild create 中文宗门验收");var g=data.of(p.getUUID());check(h,g!=null&&g.name.equals("中文宗门验收"),"Unquoted Chinese command creates guild for god-stage leader");peer.action(Actions.Kind.GUILD,"rename 合欢验收宗",0);check(h,g.id==id&&g.name.equals("合欢验收宗")&&g.members.contains(p.getUUID()),"Form packet rename keeps ID and members");IntegrationTests.command(p,"dr guild rename 非法 名称");check(h,g.name.equals("合欢验收宗"),"Whitespace names refused");}finally{data.guilds.remove(id);Guilds.ENTER_WHEN_READY.remove(p.getUUID());}}h.succeed();}
 @GameTest(template="empty") public static void flight_qualification_collision_and_rental_clock(GameTestHelper h){var level=h.getLevel();Vec3 at=new Vec3(904.5,101,904.5);for(int x=900;x<=916;x++)for(int z=900;z<=908;z++){level.getChunk(x>>4,z>>4);level.setBlock(new BlockPos(x,100,z),Blocks.STONE.defaultBlockState(),2);for(int y=101;y<110;y++)level.setBlock(new BlockPos(x,y,z),Blocks.AIR.defaultBlockState(),2);}for(int y=101;y<=106;y++)level.setBlock(new BlockPos(910,y,904),Blocks.STONE.defaultBlockState(),2);
  try(var peer=new NativeAcceptanceTests.Peer(level,"DRFlightPhysics",at)){var p=peer.player;var r=Store.of(p);r.onboardingComplete=true;r.school=1;r.stage=6;r.mana=100;p.setOnGround(true);p.setYRot(-90);SwordFlight.toggle(p);check(h,p.getVehicle() instanceof SwordFlight.Sword,"Gold-core sword class can mount");var sword=(SwordFlight.Sword)p.getVehicle();for(int i=0;i<30;i++){sword.bits=1;sword.lastInputTick=level.getGameTime();sword.tick();}check(h,sword.getX()<909.8&&sword.getX()>906,"Sword and full passenger collider stop before wall");check(h,r.flightTicks==0,"Permanent flight does not consume rental");SwordFlight.stop(p);r.school=2;r.stage=0;r.flightTicks=100;p.setPos(at.x,at.y,at.z);p.setOnGround(true);SwordFlight.toggle(p);check(h,p.getVehicle() instanceof SwordFlight.Sword,"Renter can mount");sword=(SwordFlight.Sword)p.getVehicle();sword.tick();check(h,r.flightTicks==99,"Active flight bills exactly one tick");SwordFlight.stop(p);check(h,r.flightTicks==99,"Landing pauses rental");r.flightTicks=0;SwordFlight.toggle(p);check(h,!SwordFlight.flying(p),"Expired renter cannot launch");}h.succeed();
 }
}
