VersionArgumentIndie:1
VersionArgumentIndieV2:True
VersionArgumentJavaV2:2
VersionRamType:1
VersionRamCustom:17
VersionServerLogin:4
VersionServerAuthServer:https://skin.duskrain.cn/authlib-injector
VersionServerAuthRegister:https://skin.duskrain.cn/web/registration
VersionServerAuthName:DuskRain 衣冠阁
VersionServerEnter:nbc.rainplay.cn:42741
