server {
    listen 80;
    server_name skin.duskrain.cn;
    location ^~ /.well-known/acme-challenge/ {
        root /www/wwwroot/duskrain.cn;
        default_type text/plain;
    }
    location / { return 301 https://skin.duskrain.cn$request_uri; }
}
